# Atividade 02.4 - Validando o repositório
name: Quarto Workflow

on:

  push:

jobs:
  quarto-job: 
    runs-on: ubuntu-latest
    steps:
    - run: echo "Quarto passo"
    - name: Checkout
      uses: actions/checkout@v5
    - name: Validação do repositório
      run: |
        if [ ! -f README.md ]; then
          echo "Arquivo README.md não encontrado!"
          exit 1
        fi
        if [ ! -f LICENSE ]; then
          echo "Arquivo LICENSE não encontrado!"
          exit 1
        fi
        if [ ! -f .gitignore ]; then
          echo "Arquivo .gitignore não encontrado!"
          exit 1
        fi
        echo "Validação concluída com sucesso!"
